"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ClipboardList } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { EmptyState } from "@/components/ui/empty-state";
import { useSession } from "@/features/auth/session-context";
import { useStudio } from "@/features/studio-legacy/studio-context";
import { StudioComposerBar } from "@/features/studio-legacy/StudioComposerBar";
import { generateContent, unreadMaterialsNotice, type Tier } from "@/lib/data/generation";
import {
  listGoalItemsByKind,
  createTieredGoalItemsFromPrompt,
  hasReferenceMaterial,
  type GoalItemRow,
} from "@/lib/data/classes";

const TIER_OPTIONS = [
  { key: "support", label: "Simplified" },
  { key: "extend", label: "Challenge" },
];

const TIER_BADGE: Record<string, string> = {
  support: "Simplified",
  extend: "Challenge",
};

export default function ClassHomeworkPage() {
  const { classId } = useParams<{ classId: string }>();
  const { user } = useSession();
  const { open } = useStudio();
  const [items, setItems] = useState<GoalItemRow[] | null>(null);
  const [hasReference, setHasReference] = useState<boolean | null>(null);

  const refresh = useCallback(() => {
    listGoalItemsByKind(classId, "homework").then(setItems);
    hasReferenceMaterial(classId).then(setHasReference);
  }, [classId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCreate(prompt: string, tiers: string[] = []) {
    if (!user || !hasReference) return;
    const requestedTiers = tiers as Tier[];
    const result = await generateContent("homework", classId, prompt, requestedTiers);
    await createTieredGoalItemsFromPrompt(user.id, classId, "homework", prompt, result);
    refresh();

    const notices = [unreadMaterialsNotice(result)];
    if (requestedTiers.length > 0 && !result.additional) {
      notices.push(
        "Differentiated versions aren't available yet — generated the standard worksheet only.",
      );
    }
    const notice = notices.filter(Boolean).join(" ");
    return notice ? { notice } : undefined;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-6 md:p-8">
        <p className="text-sm text-muted-foreground">
          Assignments generated by the Goal Planner, or drafted below one at a time.
        </p>
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <EmptyState
            icon={ClipboardList}
            title="No homework yet"
            description="Prompt the studio below for one assignment, or use the Goal Planner for a whole term."
          />
        ) : (
          <div className="space-y-3">
            {items.map((h) => (
              <Card key={h.id}>
                <CardContent className="flex items-center justify-between p-4">
                  <div>
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium">{h.title}</p>
                      {h.tier ? (
                        <span className="rounded-full bg-secondary px-2 py-0.5 text-xs font-medium text-secondary-foreground">
                          {TIER_BADGE[h.tier] ?? h.tier}
                        </span>
                      ) : null}
                    </div>
                    {h.detail ? (
                      <p className="text-xs text-muted-foreground">{h.detail}</p>
                    ) : null}
                  </div>
                  <div className="flex items-center gap-3">
                    <StatusPill status={h.scheduled_for ? "scheduled" : "draft"} />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        open({ title: h.title, kind: "Homework", content: h.content?.markdown })
                      }
                    >
                      Open
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
      <div className="shrink-0 border-t border-border bg-background p-4 md:px-8">
        <StudioComposerBar
          classId={classId}
          ownerId={user?.id ?? null}
          feature="homework"
          canSend={hasReference !== false}
          placeholder="e.g. A worksheet labeling the stages of cellular respiration…"
          buttonLabel="Create"
          onSubmit={handleCreate}
          onAttached={refresh}
          tierOptions={TIER_OPTIONS}
        />
      </div>
    </div>
  );
}
