"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ListChecks } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { EmptyState } from "@/components/ui/empty-state";
import { useSession } from "@/features/auth/session-context";
import { useStudio } from "@/features/studio-legacy/studio-context";
import { StudioComposerBar } from "@/features/studio-legacy/StudioComposerBar";
import { generateContent, unreadMaterialsNotice } from "@/lib/data/generation";
import {
  listAssessments,
  createAssessmentFromPrompt,
  hasReferenceMaterial,
  type AssessmentRow,
} from "@/lib/data/classes";

export default function ClassQuizzesPage() {
  const { classId } = useParams<{ classId: string }>();
  const { user } = useSession();
  const { open } = useStudio();
  const [items, setItems] = useState<AssessmentRow[] | null>(null);
  const [hasReference, setHasReference] = useState<boolean | null>(null);

  const refresh = useCallback(() => {
    listAssessments(classId, "quiz").then(setItems);
    hasReferenceMaterial(classId).then(setHasReference);
  }, [classId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCreate(prompt: string) {
    if (!user || !hasReference) return;
    const result = await generateContent("quiz", classId, prompt);
    await createAssessmentFromPrompt(user.id, classId, "quiz", result);
    refresh();
    const notice = unreadMaterialsNotice(result);
    return notice ? { notice } : undefined;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-6 md:p-8">
        <p className="text-sm text-muted-foreground">
          Auto-generated by the Goal Planner, or drafted below one at a time.
        </p>
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <EmptyState
            icon={ListChecks}
            title="No quizzes yet"
            description="Prompt the studio below for one quiz, or use the Goal Planner for a whole term."
          />
        ) : (
          <div className="space-y-3">
            {items.map((q) => (
              <Card key={q.id}>
                <CardContent className="flex items-center justify-between p-4">
                  <p className="text-sm font-medium">{q.title}</p>
                  <div className="flex items-center gap-3">
                    <StatusPill status={q.status} />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        open({
                          title: q.title,
                          kind: "Quiz",
                          content: q.content?.markdown,
                          sources: q.content?.groundedOn,
                        })
                      }
                    >
                      Review
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
      <div className="shrink-0 border-t border-border bg-background p-4 md:px-8">
        <StudioComposerBar
          classId={classId}
          ownerId={user?.id ?? null}
          feature="quiz"
          canSend={hasReference !== false}
          placeholder="e.g. A 10-question quick check on the Silk Road…"
          buttonLabel="Create"
          onSubmit={handleCreate}
          onAttached={refresh}
        />
      </div>
    </div>
  );
}
