"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Presentation } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { EmptyState } from "@/components/ui/empty-state";
import { useSession } from "@/features/auth/session-context";
import { useStudio } from "@/features/studio-legacy/studio-context";
import { StudioComposerBar } from "@/features/studio-legacy/StudioComposerBar";
import { generateContent, unreadMaterialsNotice } from "@/lib/data/generation";
import {
  listGoalItemsByKind,
  createGoalItemFromPrompt,
  hasReferenceMaterial,
  type GoalItemRow,
} from "@/lib/data/classes";

export default function ClassPresentationsPage() {
  const { classId } = useParams<{ classId: string }>();
  const { user } = useSession();
  const { open } = useStudio();
  const [items, setItems] = useState<GoalItemRow[] | null>(null);
  const [hasReference, setHasReference] = useState<boolean | null>(null);

  const refresh = useCallback(() => {
    listGoalItemsByKind(classId, "slide_deck").then(setItems);
    hasReferenceMaterial(classId).then(setHasReference);
  }, [classId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCreate(prompt: string) {
    if (!user || !hasReference) return;
    const result = await generateContent("slide_deck", classId, prompt);
    await createGoalItemFromPrompt(user.id, classId, "slide_deck", prompt, result);
    refresh();
    const notice = unreadMaterialsNotice(result);
    return notice ? { notice } : undefined;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-6 md:p-8">
        <p className="text-sm text-muted-foreground">
          Slide decks generated by the Goal Planner, or drafted below one at a time.
        </p>
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <EmptyState
            icon={Presentation}
            title="No presentations yet"
            description="Prompt the studio below for one deck, or use the Goal Planner for a whole term."
          />
        ) : (
          <div className="space-y-3">
            {items.map((p) => (
              <Card key={p.id}>
                <CardContent className="flex items-center justify-between p-4">
                  <div>
                    <p className="text-sm font-medium">{p.title}</p>
                    {p.detail ? (
                      <p className="text-xs text-muted-foreground">{p.detail}</p>
                    ) : null}
                  </div>
                  <div className="flex items-center gap-3">
                    <StatusPill status={p.scheduled_for ? "scheduled" : "draft"} />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        open({
                          title: p.title,
                          kind: "Presentation",
                          content: p.content?.markdown,
                          sources: p.content?.groundedOn,
                        })
                      }
                    >
                      Open
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
      <div className="shrink-0 border-t border-border bg-background p-4 md:px-8">
        <StudioComposerBar
          classId={classId}
          ownerId={user?.id ?? null}
          feature="slide_deck"
          canSend={hasReference !== false}
          placeholder="e.g. An 18-slide deck introducing the Silk Road…"
          buttonLabel="Create"
          onSubmit={handleCreate}
          onAttached={refresh}
        />
      </div>
    </div>
  );
}
